set(CPACK_GENERATOR "DEB")

set(CPACK_PACKAGE_NAME "plaif-moforcecontroller")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
# Map CMAKE_SYSTEM_PROCESSOR to Debian-compatible architecture
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
else()
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")
endif()
set(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}"
)
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "plaif-robot-data (>= 1.0.6), plaif-march (>= 1.5.1)")

set(CPACK_PACKAGE_VENDOR "PLAiF")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "PLAiF Force Controller Library")
set(CPACK_PACKAGE_CONTACT "lwj@plaif.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Woojae Lee")

include(CPack)
