# Get the version description
file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/version.txt" VERSION_LINES)

list(GET VERSION_LINES 0 VERSION_LINE_MAJOR)
list(GET VERSION_LINES 1 VERSION_LINE_MINOR)
list(GET VERSION_LINES 2 VERSION_LINE_PATH)
string(REGEX MATCH "^[0-9]+" PROJECT_VERSION_MAJOR "${VERSION_LINE_MAJOR}")
string(REGEX MATCH "^[0-9]+" PROJECT_VERSION_MINOR "${VERSION_LINE_MINOR}")
string(REGEX MATCH "^[0-9]+" PROJECT_VERSION_PATCH "${VERSION_LINE_PATH}")

set(CMAKE_PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")

# Get the latest Git commit hash
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE PROJECT_VERSION_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get the date of the last commit
execute_process(
    COMMAND git log -1 --format=%cd --date=format:%Y-%m-%d
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE PROJECT_VERSION_DATE
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(PROJECT_VERSION_DETAIL "${CMAKE_PROJECT_VERSION} (hash: ${PROJECT_VERSION_HASH}, date: ${PROJECT_VERSION_DATE})")

# Define values to code
add_definitions(-DPROJECT_VERSION_MAJOR="${PROJECT_VERSION_MAJOR}")
add_definitions(-DPROJECT_VERSION_MINOR="${PROJECT_VERSION_MINOR}")
add_definitions(-DPROJECT_VERSION_PATCH="${PROJECT_VERSION_PATCH}")
add_definitions(-DPROJECT_VERSION="${CMAKE_PROJECT_VERSION}")

add_definitions(-DPROJECT_VERSION_HASH="${PROJECT_VERSION_HASH}")
add_definitions(-DPROJECT_VERSION_DATE="${PROJECT_VERSION_DATE}")
add_definitions(-DPROJECT_VERSION_DETAIL="${PROJECT_VERSION_DETAIL}")