experiments:
  - name: safe_5cm_10s_twist_stand
    profile: safe_5cm_10s
    controller: twist_stand
    arm: left
    command_rate_hz: 100
    repeat: 3
    server_config: rb_servo_server/config/dual_simulator_circle_baseline_15cm16s.yaml

  - name: baseline_15cm_16s_twist_stand
    profile: circle_15cm_16s
    controller: twist_stand
    arm: left
    command_rate_hz: 100
    repeat: 3
    server_config: rb_servo_server/config/dual_simulator_circle_baseline_15cm16s.yaml

  - name: baseline_15cm_16s_twist_local
    profile: circle_15cm_16s
    controller: twist_local
    arm: left
    command_rate_hz: 100
    repeat: 3
    server_config: rb_servo_server/config/dual_simulator_circle_baseline_15cm16s.yaml

  - name: baseline_15cm_16s_linear_segments
    profile: circle_15cm_16s
    controller: linear_segments
    arm: left
    command_rate_hz: 50
    repeat: 3
    server_config: rb_servo_server/config/dual_simulator_circle_baseline_15cm16s.yaml
