#!/usr/bin/env python3
"""Re-probe logged gripper<->gripper barrier poses: how much of the reported clearance is
the convex hull's phantom, and which part of the tool is actually closest.

Until 2026-09-18 the monitor checked `pika_gripper_base_hull.STL` -- ONE convex hull over a
shape whose widest feature (the 215 mm LM guide rail) sits at the far end from its
narrowest (the 70 mm flange). The hull therefore filled the cone between them: 4.16x the
true volume. This replays the q_sent of every tick where the left<->right
`pika_gripper_base` pair was braking, and computes, at the same pose:

  * what a single hull would see    (the legacy shape, still on disk)
  * what the shipped shell sees     (pika_gripper_base_hull_{flange,housing,guide}.STL)
  * what is actually there          (raw mesh <-> raw mesh)
  * where the true witness is on each gripper, bucketed by feature

Measured 2026-09-18 on the four 09-17 15:41..16:08 runs (681 ticks): the single hull
reported p50 4.6 mm where the truth was p50 9.9 mm -- phantom p50 5.4 / max 10.0 mm -- and
the LM guide is the closest feature on one gripper in 48.7 % of them. The shipped
three-piece shell takes the phantom to p50 0.3 / max 5.5 mm and lifts 275 of the 287
sub-5 mm ticks back above the force-covered floor. No barrier margin moved.

  tools/probe_gripper_hull_phantom.py logs/servo_log_*.csv
"""
from __future__ import annotations

import argparse
import collections
import csv
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
MESH = REPO / "rb_servo_server/descriptions/meshes/robots/rb5_850e/visual/tool"
URDF = REPO / "rb_servo_server/descriptions/urdf/dual_rb5_850e_ver3.urdf"
PAIR = ("pika_gripper_base <-> ", "pika_gripper_base")
# The shipped shell, generated by rb_servo_server/tools/make_pika_tool_meshes.py.
SHELL = ("pika_gripper_base_hull_flange.STL", "pika_gripper_base_hull_housing.STL",
         "pika_gripper_base_hull_guide.STL")


def _bvh(mesh, coal):
    v = np.asarray(mesh.vertices, float) * 0.001
    f = np.asarray(mesh.faces, np.int32)
    vv = coal.StdVec_Vec3s()
    vv.extend(list(v))
    tri = coal.Triangle32 if hasattr(coal, "Triangle32") else coal.Triangle
    tt = coal.StdVec_Triangle32() if hasattr(coal, "StdVec_Triangle32") else coal.StdVec_Triangle()
    tt.extend([tri(int(a), int(b), int(c)) for a, b, c in f])
    g = coal.BVHModelOBBRSS()
    g.beginModel(len(f), len(v))
    g.addSubModel(vv, tt)
    g.endModel()
    return g


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("logs", nargs="+", type=Path)
    ap.add_argument("--stride", type=int, default=1)
    args = ap.parse_args()

    import coal
    import pinocchio as pin
    import trimesh

    base = trimesh.load(MESH / "pika_gripper_base.STL", process=False)
    hull = trimesh.load(MESH / "pika_gripper_base_hull.STL", process=False)
    true_g, hull_g = _bvh(base, coal), _bvh(hull, coal)
    shell_g = [_bvh(trimesh.load(MESH / n, process=False), coal) for n in SHELL]

    model = pin.buildModelFromUrdf(str(URDF))
    data = model.createData()
    fl = model.getFrameId("dual_rb5_850e_left_attachment_site")
    fr = model.getFrameId("dual_rb5_850e_right_attachment_site")

    def dist(g1, t1, g2, t2):
        rq, rs = coal.DistanceRequest(), coal.DistanceResult()
        coal.distance(g1, t1, g2, t2, rq, rs)
        return rs.min_distance, np.array(rs.getNearestPoint1()), np.array(rs.getNearestPoint2())

    poses = []
    for path in args.logs:
        with open(path, newline="") as fh:
            for row in csv.DictReader(fh):
                for side in ("left", "right"):
                    p = row.get(f"{side}_barrier_pair", "")
                    if PAIR[0] in p and p.endswith(PAIR[1]) \
                            and row.get(f"{side}_barrier_braking", "0") not in ("0", ""):
                        poses.append(np.deg2rad([float(row[f"{s}_q_sent_{i}"])
                                                 for s in ("left", "right") for i in range(6)]))
                        break
    poses = poses[::args.stride]
    print(f"{len(poses)} braking ticks on left_pika_gripper_base <-> right_pika_gripper_base "
          f"across {len(args.logs)} log(s)")
    if not poses:
        return 0

    def bucket(p_world, T):
        p = T.actInv(p_world) * 1000.0
        if abs(p[0]) > 90 and 135 < p[2] < 147:
            return "LM rail/carriage"
        if p[2] < 60:
            return "F/T sensor + adapters"
        if p[1] > 60:
            return "housing +y bulge"
        return "housing flank"

    checked, shipped, true, feats = [], [], [], collections.Counter()
    for q in poses:
        pin.forwardKinematics(model, data, q)
        pin.updateFramePlacements(model, data)
        TL, TR = data.oMf[fl], data.oMf[fr]
        tl = coal.Transform3s(TL.rotation, TL.translation)
        tr = coal.Transform3s(TR.rotation, TR.translation)
        checked.append(dist(hull_g, tl, hull_g, tr)[0] * 1000.0)
        dt, p1, p2 = dist(true_g, tl, true_g, tr)
        true.append(dt * 1000.0)
        feats[tuple(sorted((bucket(p1, TL), bucket(p2, TR))))] += 1
        shipped.append(min(dist(a, tl, b, tr)[0] for a in shell_g for b in shell_g) * 1000.0)

    c, t, sh = np.array(checked), np.array(true), np.array(shipped)
    q = lambda a, p: np.percentile(a, p)
    print(f"\n  ONE hull (legacy)    p5 {q(c,5):5.1f}  p50 {q(c,50):5.1f}  p95 {q(c,95):5.1f}  min {c.min():5.1f} mm")
    print(f"  SHIPPED shell (x{len(SHELL)}) p5 {q(sh,5):5.1f}  p50 {q(sh,50):5.1f}  p95 {q(sh,95):5.1f}  min {sh.min():5.1f} mm")
    print(f"  TRUE mesh<->mesh     p5 {q(t,5):5.1f}  p50 {q(t,50):5.1f}  p95 {q(t,95):5.1f}  min {t.min():5.1f} mm")
    print(f"  phantom, one hull    p50 {q(t-c,50):5.1f}  p95 {q(t-c,95):5.1f}  max {(t-c).max():5.1f} mm")
    print(f"  phantom, shipped     p50 {q(t-sh,50):5.1f}  p95 {q(t-sh,95):5.1f}  max {(t-sh).max():5.1f} mm")
    print(f"  ticks the monitor put below the 20 mm floor that were truly above it: "
          f"{int(((c < 20) & (t >= 20)).sum())} / {int((c < 20).sum())}")
    print(f"  ticks below the 5 mm force-covered floor that were truly above it:    "
          f"{int(((c < 5) & (t >= 5)).sum())} / {int((c < 5).sum())}")
    print("\n  true witness feature, per gripper pair:")
    for k, v in feats.most_common():
        print(f"    {v:6d} ({100*v/len(poses):5.1f} %)  {k[0]}  <->  {k[1]}")
    print(f"\n  ticks the shipped shell lifts back above the 5 mm force-covered floor: "
          f"{int(((c < 5) & (sh >= 5)).sum())} / {int((c < 5).sum())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
